export const Films =[
    { id: 1, Image: 'assets/images/batman_begins.jpg', Title: 'Batman Begins', 
    Year: '2005', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/FiL1_5DWV7Y?si=wMTfaLJnF6J4nwEU',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},       
    { id: 2, Image: 'assets/images/the_dark_knight.jpg', Title: 'The Dark Knight', 
    Year: '2008', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/LDG9bisJEaI?si=e-ZvbWfA33d9saxy',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 3, Image: 'assets/images/rises.jpg', Title: 'The Dark Knight Rises', 
    Year: '2013', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/g8evyE9TuYk?si=k9HFFvbhLAyeL9Q2',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 4, Image: 'assets/images/lotr1.jpg', Title: 'The Lord of the Rings: The Fellowship of the Ring', 
    Year: '2001', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/_nZdmwHrcnw?si=UABHIZ7qhM5q0Qv4',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 5, Image: 'assets/images/lotr2.jpg', Title: 'The Lord of the Rings: The Two Towers', 
    Year: '2002', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/nuTU5XcZTLA?si=a632fMiFNyADY-fG',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 6, Image: 'assets/images/lotr3.jpg', Title: 'The Lord of the Rings: The Return of the King', 
    Year: '2003', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/zckJCxYxn1g?si=5w1gc-m7g7731FSz',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 7, Image: 'assets/images/mario.jpg', Title: 'The Super Mario Bros. Movie', 
    Year: '2023', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/TnGl01FkMMo?si=NNU6P3ISfTwi6mMh',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 8, Image: 'assets/images/gump.jpg', Title: 'Forrest Gump', 
    Year: '1994', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/Mj9IA9tTfio?si=gx4B-5r1QQ1ClUFC',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},        
    { id: 9, Image: 'assets/images/gatsby.jpg', Title: 'The Great Gatsby', 
    Year: '2013', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/l6yANES3TMM?si=B4tkPD3D_d-jfBOG',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'}, 
    { id: 10, Image: 'assets/images/thebatman.jpg', Title: 'The Batman', 
    Year: '2022', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/mqqft2x_Aa4?si=KIHX-SYt3E8QZlx1',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'}, 
    { id: 11, Image: 'assets/images/interstellar.jpg', Title: 'Interstellar', 
    Year: '2014', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/zSWdZVtXT7E?si=7lNHRvjPUS1Ix_GG',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'}, 
    { id: 12, Image: 'assets/images/lalaland.jpg', Title: 'La La Land', 
    Year: '2016', Nation: 'USA', 
    Trailer: 'https://www.youtube.com/embed/0pdqf4P9MB8?si=OlAFRdaMAeBXS_qh',
    Info:'"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."'},     
  ];
  